memory_limit = 1024M

;ограничение на загрузки
upload_max_filesize = 64M
post_max_size = 64M

;xdebug
xdebug.mode=debug
xdebug.client_host=host.docker.internal
xdebug.discover_client_host=1
xdebug.start_with_request=yes

short_open_tag=false
date.timezone = "Europe/Moscow"

