user_controllers:
    resource:
        path: ../src/User/Controller/
        namespace: App\User\Controller
    type: attribute

catalog_controllers:
    resource:
        path: ../src/Catalog/Controller/
        namespace: App\Catalog\Controller
    type: attribute

login:
    path: /login
    methods: [ 'POST' ]

logout:
    path: /logout
    methods: [ ]
