user_controllers:
    resource:
        path: ../src/Modules/User/Controller/
        namespace: App\User\Controller
    type: attribute

catalog_controllers:
    resource:
        path: ../src/Modules/Catalog/Controller/
        namespace: App\Catalog\Controller
    type: attribute

application_controllers:
    resource:
        path: ../src/Application/Controller/
        namespace: App\Application\Controller
    type: attribute

login:
    path: /login
    methods: [ 'POST' ]

logout:
    path: /logout
    methods: [ ]
